version: 2.1
commands:
  deploy:
    parameters:
      to:
        type: string
      source:
        type: string
    steps:
      - run:
          name: Deploy
          command: echo deploying to << parameters.to >> SOURCE=<< parameters.source >>
executors:
  cicle_ci:
    working_directory: ~/poc-cicle-ci
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
jobs:
  build:
    executor: cicle_ci
    steps:
      - checkout
      - run:
          name: Test
          command: echo Running tests to "${CIRCLE_BRANCH}" or "${CIRCLE_TAG}"
  deploy_staging:
    executor: cicle_ci
    steps:
      - checkout
      - deploy:
          to: staging
          source: "${CIRCLE_TAG}"
  deploy_production:
    executor: cicle_ci
    steps:
      - checkout
      - deploy:
          to: production
          source: "${CIRCLE_TAG}"

workflows:
  version: 2
  general:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hold-staging:
          type: approval
          filters:
            tags:
              ignore: /.*/
          requires:
            - build
      - deploy_staging:
          filters:
            tags:
              ignore: /.*/
          requires:
            - hold-staging
  deploy-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
      - hold-staging:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - build
      - deploy_staging:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - hold-staging
      - hold-prodution:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - build
      - deploy_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - hold-prodution