version: 2.1
jobs:
  build:
    executor: cicle_ci
    docker:
      - image: debian:stretch
  test:
    executor: cicle_ci
    steps:
      - checkout
      - run:
          name: Test
          command: echo Running tests

workflows:
  version: 2
  general:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
  deploy-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
            requires:
            - build
      - hold:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - test
      - deploy_staging:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - hold
