version: 2.1
executors:
  cicle_ci:
    working_directory: ~/poc-cicle-ci
    docker:
      - image: debian:stretch
jobs:
  build:
    executor: cicle_ci
    steps:
      - checkout
      - run:
          name: Test
          command: echo Running tests to "${CIRCLE_BRANCH}"
  deploy_staging:
    executor: cicle_ci
    steps:
      - checkout
      - run:
          name: deploying
          command: echo Sending code to staging
  deploy_production:
    executor: cicle_ci
    steps:
      - checkout
      - run:
          name: deploying
          command: echo Sending code to production

workflows:
  version: 2
  general:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  deploy-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
      - hold-staging:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - build
      - deploy_staging:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - hold-staging
      - hold-prodution:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - build
      - deploy_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+\z/
          requires:
            - hold-prodution